version: "3"

services:
  app:
    image: 'ejerc-evalu:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080

  db:
    image: 'postgres:14.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=user_postgres
      - POSTGRES_PASSWORD=pass_postgres